################################### Default Configuration ############################
baseurl = "https://zixzelz.github.io/michal-company-site/"
title = "Vex | michal jackiewicz"
theme = "vex-hugo"
# post excert
summarylength = "20"
# google analytics
googleAnalytics = "" # Ex: UA-123-45
# disable language
disableLanguages = [] # disable language from here
